version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: balance
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    logging:
      driver: none
  balance:
    build: .
    image: balance:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: balance
      DATABASE_USER: root
      DATABASE_PASSWORD: secret
    links:
      - db
    command: >
      sh -c "dockerize -wait tcp://db:3306 -timeout 30s &&
            ./server"
    ports:
      - "8080:8080"
volumes:
  mysql-data: